[custom]

;RULESET
ruleset=🌍 GLOBAL,https://raw.githubusercontent.com/qichiyuhub/rule/master/ProxyLite.list
ruleset=💖 CN,https://raw.githubusercontent.com/qichiyuhub/rule/master/Direct.list
ruleset=💖 CN,[]GEOSITE,CN
ruleset=🌍 GLOBAL,[]GEOSITE,geolocation-!cn
ruleset=💖 CN,[]GEOIP,CN,no-resolve
ruleset=🐟 OTHERS,[]FINAL

;PROXYGROUP
custom_proxy_group=🌍 GLOBAL`select`[]DIRECT`[].*
custom_proxy_group=💖 CN`select`[]DIRECT`[].*
custom_proxy_group=🐟 OTHERS`select`[]DIRECT`[].*

;CONFIG
enable_rule_generator=true
overwrite_original_rules=true